"""add messages.pipeline_route

Revision ID: 079f7ca6b87b
Revises: 07e9df3b6cbc
Create Date: 2026-07-08 19:07:46.347999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '079f7ca6b87b'
down_revision: Union[str, Sequence[str], None] = '07e9df3b6cbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('pipeline_route', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'pipeline_route')
    # ### end Alembic commands ###
