"""phase 1 initial schema

Revision ID: 07e9df3b6cbc
Revises: 
Create Date: 2026-07-08 18:25:01.680159

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '07e9df3b6cbc'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('preferred_language', sa.Enum('en', 'roman_urdu', 'ur', name='preferred_language', native_enum=False, create_constraint=True, length=32), server_default='en', nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=50)), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('admin', 'agent', name='user_role', native_enum=False, create_constraint=True, length=32), server_default='agent', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index('ix_audit_log_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('bot_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('assigned_agent_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('open', 'closed', name='conversation_status', native_enum=False, create_constraint=True, length=32), server_default='open', nullable=False),
    sa.Column('flagged_high_value', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_customer_id'), 'conversations', ['customer_id'], unique=False)
    op.create_index('ix_conversations_status_last_message', 'conversations', ['status', 'last_message_at'], unique=False)
    op.create_table('knowledge_base',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('embedding', postgresql.ARRAY(sa.DOUBLE_PRECISION()), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_base_category'), 'knowledge_base', ['category'], unique=False)
    op.create_index(op.f('ix_knowledge_base_is_active'), 'knowledge_base', ['is_active'], unique=False)
    op.create_table('media_assets',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('purpose', sa.Enum('room_photo', 'rate_card', 'location', 'other', name='media_purpose', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('uploaded_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename')
    )
    op.create_table('leads',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('conversation_id', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.Enum('bot', 'manual', name='lead_source', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('interest_type', sa.Enum('room', 'event_wedding', 'corporate', 'day_trip', 'other', name='interest_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('stage', sa.Enum('new', 'contacted', 'qualified', 'booking_sent', 'won', 'lost', name='lead_stage', native_enum=False, create_constraint=True, length=32), server_default='new', nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('assigned_agent_id', sa.BigInteger(), nullable=True),
    sa.Column('follow_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_customer_id'), 'leads', ['customer_id'], unique=False)
    op.create_index(op.f('ix_leads_follow_up_at'), 'leads', ['follow_up_at'], unique=False)
    op.create_index(op.f('ix_leads_stage'), 'leads', ['stage'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('conversation_id', sa.BigInteger(), nullable=False),
    sa.Column('direction', sa.Enum('inbound', 'outbound', name='message_direction', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('sender_type', sa.Enum('customer', 'bot', 'agent', name='sender_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('content_type', sa.Enum('text', 'voice', 'image', 'pdf', 'location', name='content_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('transcription', sa.Text(), nullable=True),
    sa.Column('media_id', sa.BigInteger(), nullable=True),
    sa.Column('provider_message_id', sa.String(length=128), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['media_assets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_message_id')
    )
    op.create_index('ix_messages_conversation_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_table('unanswered_questions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('conversation_id', sa.BigInteger(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('best_similarity_score', sa.Float(), nullable=False),
    sa.Column('resolved', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unanswered_questions_conversation_id'), 'unanswered_questions', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_unanswered_questions_resolved'), 'unanswered_questions', ['resolved'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unanswered_questions_resolved'), table_name='unanswered_questions')
    op.drop_index(op.f('ix_unanswered_questions_conversation_id'), table_name='unanswered_questions')
    op.drop_table('unanswered_questions')
    op.drop_index('ix_messages_conversation_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_leads_stage'), table_name='leads')
    op.drop_index(op.f('ix_leads_follow_up_at'), table_name='leads')
    op.drop_index(op.f('ix_leads_customer_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_table('media_assets')
    op.drop_index(op.f('ix_knowledge_base_is_active'), table_name='knowledge_base')
    op.drop_index(op.f('ix_knowledge_base_category'), table_name='knowledge_base')
    op.drop_table('knowledge_base')
    op.drop_index('ix_conversations_status_last_message', table_name='conversations')
    op.drop_index(op.f('ix_conversations_customer_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index('ix_audit_log_entity', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
